version: '3.8'
services:
  datatools-server:
    build: ./datatools-server/
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./datatools-server/configurations/default/
        target: /config
      - type: bind
        source: ~/.aws
        target: /root/.aws
    depends_on:
      - mongo
      - postgres
      - datatools-ui
  datatools-ui:
    build: ./datatools-ui/
    ports:
      - "9966:80"
  mongo:
    image: mongo
    restart: always
  postgres:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: root
      POSTGRES_DB: dmtest
    image: postgres
    restart: always