apiVersion: v2
name: mongodb
description: MongoDB Kubernetes Community Operator
type: application
version: 0.7.8
appVersion: 0.7.8
dependencies:
- name: community-operator-crds
  version: 0.7.8
  repository: https://mongodb.github.io/helm-charts
  condition: community-operator-crds.enabled