apiVersion: v1
kind: ConfigMap
metadata:
  name: ibi-datatools-server-configmap
data:
  # The env.yml file content is based on the env.yml.tmp file. See the
  # basic configuration section of the documentation for more info:
  # https://data-tools-docs.ibi-transit.com/en/latest/dev/deployment/#installation-and-basic-configuration
  env.yml: |
    # This client ID refers to the UI client in Auth0.
    AUTH0_CLIENT_ID: your-auth0-client-id
    AUTH0_DOMAIN: your-auth0-domain
    # Note: One of AUTH0_SECRET or AUTH0_PUBLIC_KEY should be used depending on the signing algorithm set on the client.
    # It seems that newer Auth0 accounts (2017 and later) might default to RS256 (public key).
    # AUTH0_SECRET: your-auth0-secret # uses HS256 signing algorithm
    AUTH0_PUBLIC_KEY: /path/to/auth0.pem # uses RS256 signing algorithm
    # This client/secret pair refer to a machine-to-machine Auth0 application used to access the Management API.
    AUTH0_API_CLIENT: your-api-client-id
    AUTH0_API_SECRET: your-api-secret-id
    DISABLE_AUTH: false

    OSM_VEX: http://localhost:1000

    SPARKPOST_KEY: your-sparkpost-key
    SPARKPOST_EMAIL: email@example.com

    GTFS_DATABASE_URL: jdbc:postgresql://postgres/dmtest # If running via docker, this is jdbc:postgresql://postgres/dmtest
    # GTFS_DATABASE_USER:
    # GTFS_DATABASE_PASSWORD:

    MONGO_DB_NAME: catalogue
    MONGO_HOST: mongodb-service:27017 # If running via docker, this is mongo:27017
    MONGO_PASSWORD: password
    MONGO_USER: admin

  # The server.yml file content is based on the server.yml.tmp file. See the
  # basic configuration section of the documentation for more info:
  # https://data-tools-docs.ibi-transit.com/en/latest/dev/deployment/#installation-and-basic-configuration
  server.yml: |
    application:
      title: Data Tools
      logo: https://d2tyb7byn1fef9.cloudfront.net/ibi_group-128x128.png
      logo_large: https://d2tyb7byn1fef9.cloudfront.net/ibi_group_black-512x512.png
      client_assets_url: https://example.com
      shortcut_icon_url: https://d2tyb7byn1fef9.cloudfront.net/ibi-logo-original%402x.png
      public_url: http://localhost:9966
      notifications_enabled: false
      docs_url: http://conveyal-data-tools.readthedocs.org
      support_email: support@ibigroup.com
      port: 4000
      data:
        gtfs: /tmp
        use_s3_storage: false
        s3_region: us-east-1
        gtfs_s3_bucket: bucket-name
    modules:
      enterprise:
        enabled: false
      editor:
        enabled: true
      deployment:
        enabled: true
        ec2:
          enabled: false
          default_ami: ami-your-ami-id
        # Note: using a cloudfront URL for these download URLs will greatly
        # increase download/deploy speed.
        otp_download_url: https://optional-otp-repo.com
      user_admin:
        enabled: true
      gtfsapi:
        enabled: true
        load_on_fetch: false
        # use_extension: mtc
        # update_frequency: 30 # in seconds
      manager:
        normalizeFieldTransformation:
          # Enter capitalization exceptions (e.g. acronyms), in the desired case, and separated by commas.
          defaultCapitalizationExceptions:
            - ACE
            - BART
          # Enter substitutions (e.g. substitute '@' with 'at'), one dashed entry for each substitution, with:
          # - pattern: the regex string pattern that will be replaced,
          # - replacement: the replacement string for that pattern,
          # - normalizeSpace: if true, the resulting field value will include one space before and after the replacement string.
          #       Note: if the replacement must be blank, then normalizeSpace should be set to false
          #       and whitespace management should be handled in pattern instead.
          # Substitutions are executed in order they appear in the list.
          defaultSubstitutions:
            - description: "Replace '@' with 'at', and normalize space."
              pattern: "@"
              replacement: at
              normalizeSpace: true
            - description: "Replace '+' (\\+ in regex) and '&' with 'and', and normalize space."
              pattern: "[\\+&]"
              replacement: and
              normalizeSpace: true
    extensions:
      transitland:
        enabled: true
        api: https://transit.land/api/v1/feeds
      transitfeeds:
        enabled: true
        api: http://api.transitfeeds.com/v1/getFeeds
