apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-storageclass
  local:
    path: /mnt/data
  
  # Step 3.2 of the guide at https://phoenixnap.com/kb/kubernetes-mongodb
  # instructs us to set the nodeAffinity. This seems superfluous for now, since
  # all of our nodes look the same, but when we skip this we get an error:
  #
  # ```
  # The PersistentVolume "mongodb-pv" is invalid: spec.nodeAffinity: Required value: Local volume requires node affinity.
  # ```
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: customlabel
          operator: In
          values:
            - thirdpartytools