apiVersion: apps/v1
kind: Deployment
metadata:
  name: datatools-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: datatools-ui
  strategy: {}
  template:
    metadata:
      labels:
        name: datatools-ui
    spec:
      containers:
        - image: docker.io/library/ibi-datatools-ui:latest
          imagePullPolicy: Never
          name: datatools-ui
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: datatools-ui-service
spec:
  ports:
    - name: "9966"
      port: 9966
      targetPort: 80
  selector:
    name: datatools-ui
status:
  loadBalancer: {}
