apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  strategy: {}
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          resources: {}
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - name: "mongo-port"
      port: 27017
      targetPort: 27017
  selector:
    name: mongo
