apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  strategy: {}
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: dmtest
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_USER
              value: root
          image: postgres
          name: postgres
          resources: {}
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - name: "postgres-port"
      port: 5432
      targetPort: 5432
  selector:
    name: postgres
