name: Build and push ibi-datatools-ui image

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build-ibi-datatools-ui-image.yml'
      - 'scripts/configure_ui.sh'
      - 'scripts/datatools-ui-Dockerfile'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build-ibi-datatools-ui-image.yml'
      - 'scripts/configure_ui.sh'
      - 'scripts/datatools-ui-Dockerfile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Steps should be:
  # 0. Check out this repo
  # 1. Clone the latest release of datatools-ui repo (https://github.com/ibi-group/datatools-ui) to the folder `datatools-ui`
  # 2. Copy over the dockerfile from datatools-infra/scripts/datatools-ui-Dockerfile to datatools-ui/Dockerfile
  # 5. Build the ibi-datatools-ui image from the Dockerfile in the datatools-ui folder
  # 6. Push the datatools-ui image to the GitHub Container Registry

  build_push:
    name: Package docker image
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Check out the infra repo
        uses: actions/checkout@v2
      - name: Check out the datatools-ui repo
        uses: actions/checkout@v2
        with:
          repository: ibi-group/datatools-ui
          path: datatools-ui
      - name: Generate the configuration files
        run: scripts/configure_ui.sh
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "GITHUB_SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - uses: docker/build-push-action@v2
        with:
          context: ./datatools-ui
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{github.repository}}/ibi-datatools-ui:${{ env.GITHUB_SHORT_SHA }}
